// Generated by gencpp from file sabertooth_ctrl/TwoFloats.msg
// DO NOT EDIT!


#ifndef SABERTOOTH_CTRL_MESSAGE_TWOFLOATS_H
#define SABERTOOTH_CTRL_MESSAGE_TWOFLOATS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sabertooth_ctrl
{
template <class ContainerAllocator>
struct TwoFloats_
{
  typedef TwoFloats_<ContainerAllocator> Type;

  TwoFloats_()
    : left(0.0)
    , right(0.0)  {
    }
  TwoFloats_(const ContainerAllocator& _alloc)
    : left(0.0)
    , right(0.0)  {
  (void)_alloc;
    }



   typedef float _left_type;
  _left_type left;

   typedef float _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::sabertooth_ctrl::TwoFloats_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sabertooth_ctrl::TwoFloats_<ContainerAllocator> const> ConstPtr;

}; // struct TwoFloats_

typedef ::sabertooth_ctrl::TwoFloats_<std::allocator<void> > TwoFloats;

typedef boost::shared_ptr< ::sabertooth_ctrl::TwoFloats > TwoFloatsPtr;
typedef boost::shared_ptr< ::sabertooth_ctrl::TwoFloats const> TwoFloatsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sabertooth_ctrl::TwoFloats_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sabertooth_ctrl::TwoFloats_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sabertooth_ctrl::TwoFloats_<ContainerAllocator1> & lhs, const ::sabertooth_ctrl::TwoFloats_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sabertooth_ctrl::TwoFloats_<ContainerAllocator1> & lhs, const ::sabertooth_ctrl::TwoFloats_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sabertooth_ctrl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sabertooth_ctrl::TwoFloats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sabertooth_ctrl::TwoFloats_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sabertooth_ctrl::TwoFloats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sabertooth_ctrl::TwoFloats_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sabertooth_ctrl::TwoFloats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sabertooth_ctrl::TwoFloats_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sabertooth_ctrl::TwoFloats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a927990ab5d5c3d628e2d52b8533e52";
  }

  static const char* value(const ::sabertooth_ctrl::TwoFloats_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a927990ab5d5c3dULL;
  static const uint64_t static_value2 = 0x628e2d52b8533e52ULL;
};

template<class ContainerAllocator>
struct DataType< ::sabertooth_ctrl::TwoFloats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sabertooth_ctrl/TwoFloats";
  }

  static const char* value(const ::sabertooth_ctrl::TwoFloats_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sabertooth_ctrl::TwoFloats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 left\n"
"float32 right\n"
;
  }

  static const char* value(const ::sabertooth_ctrl::TwoFloats_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sabertooth_ctrl::TwoFloats_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TwoFloats_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sabertooth_ctrl::TwoFloats_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sabertooth_ctrl::TwoFloats_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SABERTOOTH_CTRL_MESSAGE_TWOFLOATS_H
