// Generated by gencpp from file sabertooth_ctrl/TwoInts.msg
// DO NOT EDIT!


#ifndef SABERTOOTH_CTRL_MESSAGE_TWOINTS_H
#define SABERTOOTH_CTRL_MESSAGE_TWOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sabertooth_ctrl
{
template <class ContainerAllocator>
struct TwoInts_
{
  typedef TwoInts_<ContainerAllocator> Type;

  TwoInts_()
    : left(0)
    , right(0)  {
    }
  TwoInts_(const ContainerAllocator& _alloc)
    : left(0)
    , right(0)  {
  (void)_alloc;
    }



   typedef int32_t _left_type;
  _left_type left;

   typedef int32_t _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::sabertooth_ctrl::TwoInts_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sabertooth_ctrl::TwoInts_<ContainerAllocator> const> ConstPtr;

}; // struct TwoInts_

typedef ::sabertooth_ctrl::TwoInts_<std::allocator<void> > TwoInts;

typedef boost::shared_ptr< ::sabertooth_ctrl::TwoInts > TwoIntsPtr;
typedef boost::shared_ptr< ::sabertooth_ctrl::TwoInts const> TwoIntsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sabertooth_ctrl::TwoInts_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sabertooth_ctrl::TwoInts_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sabertooth_ctrl::TwoInts_<ContainerAllocator1> & lhs, const ::sabertooth_ctrl::TwoInts_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sabertooth_ctrl::TwoInts_<ContainerAllocator1> & lhs, const ::sabertooth_ctrl::TwoInts_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sabertooth_ctrl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sabertooth_ctrl::TwoInts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sabertooth_ctrl::TwoInts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sabertooth_ctrl::TwoInts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sabertooth_ctrl::TwoInts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sabertooth_ctrl::TwoInts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sabertooth_ctrl::TwoInts_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sabertooth_ctrl::TwoInts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "febc810ab9cc360ca3f47fcee4f2ba71";
  }

  static const char* value(const ::sabertooth_ctrl::TwoInts_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfebc810ab9cc360cULL;
  static const uint64_t static_value2 = 0xa3f47fcee4f2ba71ULL;
};

template<class ContainerAllocator>
struct DataType< ::sabertooth_ctrl::TwoInts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sabertooth_ctrl/TwoInts";
  }

  static const char* value(const ::sabertooth_ctrl::TwoInts_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sabertooth_ctrl::TwoInts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 left\n"
"int32 right\n"
;
  }

  static const char* value(const ::sabertooth_ctrl::TwoInts_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sabertooth_ctrl::TwoInts_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TwoInts_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sabertooth_ctrl::TwoInts_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sabertooth_ctrl::TwoInts_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SABERTOOTH_CTRL_MESSAGE_TWOINTS_H
